(function() {var implementors = {};
implementors["lazy_static"] = [];
implementors["libc"] = [];
implementors["num"] = [];
implementors["sdl2"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/filesystem/enum.PrefPathError.html' title='sdl2::filesystem::PrefPathError'>PrefPathError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/controller/enum.AddMappingError.html' title='sdl2::controller::AddMappingError'>AddMappingError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/video/enum.WindowBuildError.html' title='sdl2::video::WindowBuildError'>WindowBuildError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/render/enum.TextureValueError.html' title='sdl2::render::TextureValueError'>TextureValueError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/render/enum.UpdateTextureError.html' title='sdl2::render::UpdateTextureError'>UpdateTextureError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/render/enum.UpdateTextureYUVError.html' title='sdl2::render::UpdateTextureYUVError'>UpdateTextureYUVError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/enum.Error.html' title='sdl2::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/messagebox/enum.ShowMessageError.html' title='sdl2::messagebox::ShowMessageError'>ShowMessageError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/ttf/enum.FontError.html' title='sdl2::ttf::FontError'>FontError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/ttf/enum.InitError.html' title='sdl2::ttf::InitError'>InitError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='sdl2/enum.IntegerOrSdlError.html' title='sdl2::IntegerOrSdlError'>IntegerOrSdlError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
